-- Roles y bases de desarrollo. SUPERUSER solo en local; no replicar en produccion.
CREATE ROLE developer WITH LOGIN SUPERUSER CREATEDB CREATEROLE NOREPLICATION NOBYPASSRLS PASSWORD 'developer';
CREATE ROLE tester WITH LOGIN SUPERUSER CREATEDB CREATEROLE NOREPLICATION NOBYPASSRLS PASSWORD 'tester';
CREATE ROLE auditor WITH LOGIN SUPERUSER CREATEDB CREATEROLE NOREPLICATION NOBYPASSRLS PASSWORD 'auditor';
CREATE ROLE pulse WITH LOGIN SUPERUSER CREATEDB CREATEROLE NOREPLICATION NOBYPASSRLS PASSWORD 'pulse';
CREATE ROLE keycloak WITH LOGIN SUPERUSER CREATEDB CREATEROLE NOREPLICATION NOBYPASSRLS PASSWORD 'keycloak';

CREATE DATABASE development WITH OWNER developer ENCODING 'UTF8' LOCALE_PROVIDER icu ICU_LOCALE 'es-CL' TEMPLATE template_full_cl;
CREATE DATABASE testing WITH OWNER tester ENCODING 'UTF8' LOCALE_PROVIDER icu ICU_LOCALE 'es-CL' TEMPLATE template_full_cl;
CREATE DATABASE auditing WITH OWNER auditor ENCODING 'UTF8' LOCALE_PROVIDER icu ICU_LOCALE 'es-CL' TEMPLATE template_full_cl;
CREATE DATABASE pulse WITH OWNER pulse ENCODING 'UTF8' LOCALE_PROVIDER icu ICU_LOCALE 'es-CL' TEMPLATE template_full_cl;
CREATE DATABASE keycloak WITH OWNER keycloak ENCODING 'UTF8' LOCALE_PROVIDER icu ICU_LOCALE 'es-CL' TEMPLATE template_full_cl;
